name = "generator-fuel-calculator-2"
main = "worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "generator-fuel-db"
database_id = "f1991b43-7083-4d82-b6e0-0c32abb54374"

[assets]
directory = "./public"
binding = "ASSETS"
[ai]
binding = "AI"
